---
title: "rcontroll practical work"
date: today
date-format: medium
format: 
  gfm:
    toc: true
    toc-depth: 1
---

🇬🇧 `rcontroll` practical work: An R Interface for the Individual-Based
Forest Dynamics Simulator TROLL.

🇫🇷 Travaux Pratiques sur `rcontroll`: Une interface R pour le simulateur
de dynamique forestière basé sur les individus TROLL.

🇧🇷 Trabalhos Práticos sobre `rcontroll`: Uma interface R para o simulador
de dinâmica florestal baseado em indivíduos TROLL.

## INPA-2026 Instituto Nacional de Pesquisas da Amazônia

🇧🇷 Manaus, Brazil: workshop on tropical forest dynamics modeling at
Ducke Research Station, Manaus, Brazil, 6-10 April 2026 with
National Institute of Amazonian Research ([INPA](https://www.gov.br/inpa/pt-br)).

* [Installation instructions 🇧🇷](https://github.com/sylvainschmitt/rcontroll_tp/wiki/Instala%C3%A7%C3%A3o-%E2%80%90-Manaus)
* [Installation instructions 🇫🇷](https://github.com/sylvainschmitt/rcontroll_tp/wiki/Installation-%E2%80%90-Manaus)
* [Day 1 - Hands-on TROLL 3 discovery with `rcontroll` 🇬🇧](https://sylvainschmitt.github.io/rcontroll_tp/inpa_2026/day1.html)
* [Dia 1 - Introdução prática ao TROLL 3 com `rcontroll` 🇧🇷](https://sylvainschmitt.github.io/rcontroll_tp/inpa_2026/day1_pt.html)
* [Day 2 - Hands-on TROLL 4 discovery with `rcontroll` 🇬🇧](https://sylvainschmitt.github.io/rcontroll_tp/inpa_2026/day2.html)
* [Dia 2 - Introdução prática ao TROLL 4 com `rcontroll` 🇧🇷](https://sylvainschmitt.github.io/rcontroll_tp/inpa_2026/day2_pt.html)
* [Day 3 - Hands-on TROLL advanced usage 🇬🇧](https://sylvainschmitt.github.io/rcontroll_tp/inpa_2026/day3.html)
* [Dia 3 - Uso avançado do TROLL com `rcontroll` 🇧🇷](https://sylvainschmitt.github.io/rcontroll_tp/inpa_2026/day3_pt.html)

## UCL-2025 Université Catholique de Louvain-la-Neuve

🇧🇪 Louvain-la-Neuve, Belgium: teaching in the field of tropical
  forestry and international forestry issues from the Faculty of
  Bioengineering at the Université Catholique de Louvain-la-Neuve
  ([UCL](https://www.uclouvain.be/fr/facultes/agro)).

* [Installation instructions](https://github.com/sylvainschmitt/rcontroll_tp/wiki/Installation-%E2%80%90-Louvain)
* [Support](https://sylvainschmitt.github.io/rcontroll_tp/ucl_2025/teacher.html)
